<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ZzzAutoSign</AssemblyName>
    <RootNamespace>ZzzAutoSign</RootNamespace>
    <!-- 托盘程序需要，避免控制台窗口 -->
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />
  </ItemGroup>

</Project>
